### PR TITLE
Major enhancements...

### PR DESCRIPTION
**Pull request by RicoAntonioFelix**
Re-engineered the project structure...

### CODE REVIEW

**Comment by solusipse** [comment]
These are massive changes, most of them I would merge into project right now, but there are also some things that need clarification.
As I see, you propose to make this library header only. I believe it's rather C++ practice, but since this is a small project, I'm ok with that, there are many benefits of such design.
Other thing is that `UREQ_ALL` handler does not work anymore, could you please take a look at this issue? I need to do some more tests and then I'll merge it.
Awesome job, since now this project was just a draft, you made a proper library out of it. Thank you.

**Comment by RicoAntonioFelix** [comment]
I'll have a look at the issue with 'UREQ_ALL` and report back with my findings...

**Comment by solusipse** [comment]
Ok, thank you.

**Comment by RicoAntonioFelix** [comment]
I can't seem to find the issue... :disappointed: 

Can you describe what I'm suppose to look for?

**Comment by solusipse** [comment]
At line 251 in `ureq_impl.h` change

```
if (!strcmp(UREQ_ALL, pages[i].method)) {
```

to

```
if (strcmp(UREQ_ALL, pages[i].method) != 0) {
```

Works for me now.

**Comment by RicoAntonioFelix** [comment]
Fixed...

Anything else that crops up while testing let me know...

**Comment by solusipse** [comment]
Everything seems to be working fine now, it still needs to be tested on ESP8266, but I'll do it later. Many thanks for all these changes, I'm merging it.

**Comment by RicoAntonioFelix** [comment]
You're welcome... :v:

**Comment by solusipse** [comment]
I'd like to change `internal` directory name to `include` and `ureq_impl.h` to `ureq_core.h`, are you ok with that?

**Comment by RicoAntonioFelix** [comment]
Sounds good to me...

**Pull request merged**
