### PR TITLE
Minor enhancements...

### PR DESCRIPTION
**Pull request by RicoAntonioFelix**
## Changes in `ureq_core.h`
- Changed inclusion guard to match file-name
- Guard against invalid request in ureq_get_header function
- Calculate header length once in ureq_generate_response_header function
- Refactored ureq_init function to make it more concise and eliminate double checking
## Changes in `ureq_defines.h`
- Added a macro to allow initialization of an `HttpRequest` object in one line removing clutter and potential for error
## Changes in README.md
- Updated license section to include a link to the license file
- Added extra status badges
- Added link to image of device

### CODE REVIEW

**Comment by solusipse** [comment]
Thank you. I'd love to merge this one, but I don't think that doing #16 is a good idea right now, when project isn't still mature. Could you remove these commits, please? We'll replace quotes with brackets in the future, after first release.

**Comment by RicoAntonioFelix** [comment]
I suppose this should be satisfactory now...

**Comment by solusipse** [comment]
Awesome, great job. Thank you!

**Comment by RicoAntonioFelix** [comment]
You're welcome... :v:

**Pull request merged**
